//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineCocoa

final class ___VARIABLE_moduleName___ViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: ___VARIABLE_moduleName___PresenterInterface!
    
    // MARK: - Private properties -
    
    private var cancellables: Set<AnyCancellable> = []
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // TODO: setup view
        // TODO: bindings
        
        presenter.events.send(.viewDidLoad)
    }
    
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___ViewInterface {
}
