//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class ___VARIABLE_moduleName___Presenter {

    // MARK: - Public properties -
    
    let actions = PublishSubject<___VARIABLE_moduleName___PresenterActions>()
    let events = PublishSubject<___VARIABLE_moduleName___PresenterEvents>()
    
    let isLoading = BehaviorRelay<Bool>(value: false)
    let error = PublishSubject<Error>()

    // MARK: - Private properties -

    private unowned let view: ___VARIABLE_moduleName___ViewInterface
    private let interactor: ___VARIABLE_moduleName___InteractorInterface
    private let wireframe: ___VARIABLE_moduleName___WireframeInterface
    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    init(view: ___VARIABLE_moduleName___ViewInterface, interactor: ___VARIABLE_moduleName___InteractorInterface, wireframe: ___VARIABLE_moduleName___WireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.setup()
    }
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___PresenterInterface {
    private func setup() {
        actions.subscribe(onNext: { [weak self] action in
            switch action {
            case .viewDidLoad:
                break
            }
        }).disposed(by: disposeBag)
        
        events.subscribe(onNext: { [weak self] action in
            switch action {
            case .viewDidLoad:
                break
            }
        }).disposed(by: disposeBag)
    }
}
