//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ___VARIABLE_moduleName___ViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ___VARIABLE_moduleName___PresenterInterface!

    // MARK: - Lifecycle -

    // MARK: - Private properties -
    
    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
//        presenter.isLoading
//            .bind(to: rx.isLoading)
//            .disposed(by: disposeBag)
//        presenter.error
//            .bind(to: rx.displayableError)
//            .disposed(by: disposeBag)

		// TODO: setup view

        presenter.actions.onNext(.viewDidLoad)
        presenter.events.onNext(.viewDidLoad)
    }

}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___ViewInterface {
}
