//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ___VARIABLE_moduleName___WireframeInterface: WireframeInterface {
}

protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

struct ___VARIABLE_moduleName___PresenterInputs {
	
}

struct ___VARIABLE_moduleName___PresenterOutputs {
	
}

enum ___VARIABLE_moduleName___PresenterEvents {
    case viewDidLoad
}

protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
	var inputs: ___VARIABLE_moduleName___PresenterInputs { get }
	var outputs: ___VARIABLE_moduleName___PresenterOutputs { get }
    var events: PublishSubject<___VARIABLE_moduleName___PresenterEvents> { get }
}

protocol ___VARIABLE_moduleName___FormatterInterface: FormatterInterface {
}

protocol ___VARIABLE_moduleName___InteractorInterface: InteractorInterface {
}
